commanders:
  Abathur:
    date: 2016-05-17
    race: Zerg
    sc2cooplink: https://starcraft2coop.com/commanders/abathur
    wikilink: https://starcraft.fandom.com/wiki/Abathur_\(Co-op_Missions\)
  Alarak:
    date: 2016-09-13
    race: Protoss
    sc2cooplink: https://starcraft2coop.com/commanders/alarak
    wikilink: https://starcraft.fandom.com/wiki/Alarak_\(Co-op_Missions\)
  Artanis:
    date: 2015-10-06
    race: Protoss
    sc2cooplink: https://starcraft2coop.com/commanders/artanis
    wikilink: https://starcraft.fandom.com/wiki/Artanis_\(Co-op_Missions\)
  Dehaka:
    date: 2017-07-18
    race: Zerg
    sc2cooplink: https://starcraft2coop.com/commanders/dehaka
    wikilink: https://starcraft.fandom.com/wiki/Dehaka_\(Co-op_Missions\)
  Fenix:
    date: 2017-05-02
    race: Protoss
    sc2cooplink: https://starcraft2coop.com/commanders/fenix
    wikilink: https://starcraft.fandom.com/wiki/Fenix_\(Co-op_Missions\)
  Han & Horner:
    date: 2017-11-14
    race: Terran
    sc2cooplink: https://starcraft2coop.com/commanders/horner
    wikilink: https://starcraft.fandom.com/wiki/Mira_Han_and_Matt_Horner_\(Co-op_Missions\)
  Karax:
    date: 2015-12-15
    race: Protoss
    sc2cooplink: https://starcraft2coop.com/commanders/karax
    wikilink: https://starcraft.fandom.com/wiki/Karax_\(Co-op_Missions\)
  Kerrigan:
    date: 2015-10-06
    race: Zerg
    sc2cooplink: https://starcraft2coop.com/commanders/kerrigan
    wikilink: https://starcraft.fandom.com/wiki/Sarah_Kerrigan_\(Co-op_Missions\)
  Mengsk:
    date: 2019-11-26
    race: Terran
    sc2cooplink: https://starcraft2coop.com/commanders/mengsk
    wikilink: https://starcraft.fandom.com/wiki/Arcturus_Mengsk_\(Co-op_Missions\)
  Nova:
    date: 2016-10-18
    race: Terran
    sc2cooplink: https://starcraft2coop.com/commanders/nova
    wikilink: https://starcraft.fandom.com/wiki/Nova_Terra_\(Co-op_Missions\)
  Raynor:
    date: 2015-10-06
    race: Terran
    sc2cooplink: https://starcraft2coop.com/commanders/raynor
    wikilink: https://starcraft.fandom.com/wiki/Jim_Raynor_\(Co-op_Missions\)
  Stetmann:
    date: 2019-05-21
    race: Zerg
    sc2cooplink: https://starcraft2coop.com/commanders/stetmann
    wikilink: https://starcraft.fandom.com/wiki/Egon_Stetmann_\(Co-op_Missions\)
  Stukov:
    date: 2016-12-13
    race: Zerg
    sc2cooplink: https://starcraft2coop.com/commanders/stukov
    wikilink: https://starcraft.fandom.com/wiki/Alexei_Stukov_\(Co-op_Missions\)
  Swann:
    date: 2015-10-06
    race: Terran
    sc2cooplink: https://starcraft2coop.com/commanders/swann
    wikilink: https://starcraft.fandom.com/wiki/Rory_Swann_\(Co-op_Missions\)
  Tychus:
    date: 2018-09-04
    race: Terran
    sc2cooplink: https://starcraft2coop.com/commanders/tychus
    wikilink: https://starcraft.fandom.com/wiki/Tychus_Findlay_\(Co-op_Missions\)
  Vorazun:
    date: 2015-10-06
    race: Protoss
    sc2cooplink: https://starcraft2coop.com/commanders/vorazun
    wikilink: https://starcraft.fandom.com/wiki/Vorazun_\(Co-op_Missions\)
  Zagara:
    date: 2015-10-06
    race: Zerg
    sc2cooplink: https://starcraft2coop.com/commanders/zagara
    wikilink: https://starcraft.fandom.com/wiki/Zagara_\(Co-op_Missions\)
  Zeratul:
    date: 2018-11-13
    race: Protoss
    sc2cooplink: https://starcraft2coop.com/commanders/zeratul
    wikilink: https://starcraft.fandom.com/wiki/Egon_Stetmann_\(Co-op_Missions\)
posthistory: null
